### ISSUE TITLE
Overall design

### ISSUE THREAD

**Issue by dcousens** [weilu/cb-wallet#1]
As discussed in https://github.com/bitcoinjs/bitcoinjs-lib/issues/260#issuecomment-52448803, I feel like the 'all-in-one' design of the `Wallet` right now is too overwhelming, and leads to bad separation of concerns.

In essence the design needs to cater for three things:
- Provide a simplified key management API,
  - With the ability to generate/iterate addresses using BIP32,
  - and the ability to sign transactions with addresses
- Provide unspent Transaction outputs aggregation,
  - With functionality to provide candidates for a particular output value, and
  - Capability to check balance based on blockHeight/confirmations
- Unspent Transaction output utility functions, such as
  - Create Transaction from inputs, outputs and optional change address, fee

As an example of what this API might look like, here is an example for spending:

``` javascript
var satoshis = 1e5
var inputs = unspents.candidates(satoshis)
var addresses = inputs.filter(function(inputs) { return u.address })

var tx = utils.createTransaction(inputs, outputs, { change: '18eRuS...' , fee: 0 })

wallet.sign(tx).with(addresses)
blockchain.propagate(tx, function(err) {
   ...
})
```

Then perhaps even a check to see if your address is used might just be:

``` javascript
if (unspents.contains(address)) {
  wallet.next()
}
```

Thoughts?

Using [BIP32-utils](https://github.com/dcousens/bip32-utils) discovery might be:

``` javascript
bip32utils.discovery(wallet.getExternalAccount(), 20, function(addresses, callback) {
  blockchain.addresses.summary(addresses, function(err, results) {
    if (err) return callback(err)

    var areSpent = results.map(function(result) {
      return result.totalReceived > 0
    })

    callback(undefined, areSpent)
  })
}, function(err, k) {
  if (err) return done(err)

  console.warn('Discovered ' + k + ' addresses')
  wallet.generate(0, k)

  done()
})
```

**Comment by dcousens** [comment]
Again, that example code isn't set in stone, but I really want to make a separation of:
- Address/key management, and
- Unspent management

The result will be more easily testable, and have clearer separation of concerns.  It also means we can start plug & playing different algorithms for both without having to re-writing the entire `Wallet` abstraction. 

For example, we might not even want to use BIP32 behind `Wallet`, but some other deterministic structure.
Using this design, we could swap that out quite easily.

**Comment by weilu** [comment]
I see where you are from. As where it stands, I see unspent management being taken care of by bitcoin-tx-graph, all that the wallet does is essentially just https://github.com/weilu/cb-wallet/blob/master/index.js#L148-L151, then parse it into an easily consumable internal format by `createTx`. I'm not sure I want to expose unspents at an API level -- utxo is not a well-defined format and is only specific to wallets as a snapshot. 

The "swap out bip32 for another deterministic structure" is a valid use case, but I'm reluctant to create abstractions until there's someone who needs it in real life. That being said, current `createTx` is merely a feature equivalent of what's in bitcoinjs' wallet. I'd like to add more detailed validation/error handling to it. And perhaps we can talk about adding unconfirmed tx spending rules. I'm definitely going to move some stuff out as the logic and complexity grow.

**Comment by dcousens** [comment]
My point with `unspents` as an abstraction was that a wallet at any point in time doesn't necessarily care about its history, only what it has at that time (as you call, a snapshot)

However, to track and manage unspents in an scalable way, you would use something like bitcoin-tx-graph.  Alternative implementations should be able to swap out these unspent managers with simple snapshot taking (aka, using unspent APIs), or their own custom designs.
This isn't even over-engineering, its just clear separation of concerns IMHO.

> The "swap out bip32 for another deterministic structure" is a valid use case, but I'm reluctant to create abstractions until there's someone who needs it in real life. 

BIP43/BIP44, or even a non-deterministic Wallet such as what exists in bitcoin-qt.

**Comment by dcousens** [comment]
I eventually started work on this design separation in https://github.com/dcousens/bip32-wallet.   I hope to make further progress by separating blockchain/consensus and unspent tracking,  key management, and input selection.
